<a href="https://colab.research.google.com/github/PaclonkMei/MineriAdDatOs_177876/blob/main/Mineria_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer Parcial

### Introducción

https://jakevdp.github.io/PythonDataScienceHandbook/01.01-help-and-documentation.html

#### Conceptos

https://www.ibm.com/es-es/think/topics/data-mining

#### Ciencia de Datos

Ayuda y documentacion en Python

In [ ]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de pedir ayuda
len?

In [ ]:
#Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
#Otra forma de pedir ayuda con una lista
L?

In [ ]:
#Ejemplo de funcion
def square(a):
  return a ** 2

In [ ]:
help(square)

Help on function square in module __main__:

square(a)



In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

IPython Magic Commands


In [ ]:
#Evalua el desempeño de la expresion respecto al tiempo, solo evalua una linea
%timeit L = [n ** 2 for n in range(1000)]

70 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#El doble porcentaje es para evaluar el desempeño de varias lineas de tiempo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

81.4 µs ± 9.88 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
ls

sample_data/


In [ ]:
!pwd

/content


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "Héloooou"

In [ ]:
!echo = {message}

= Héloooou


In [ ]:
%cd /content/

/content


In [ ]:
%ls

sample_data/


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'f2883a46d164',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in IPython

In [ ]:
#Importa numpy y renombralo como np
import numpy as np

In [ ]:
#un arregl lineal de enteros, ND array, number dimention
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#al hacer una lista con np, esta castea los diferentes numeros en un tipo, en este caso, flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#podemos especificar que tipo queremos castear
np.array([3.14, 4, 2, 3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [ ]:
np.array([3.14, 4, 2, 3], dtype='int')

array([3, 4, 2, 3])

In [ ]:
#En rango no se toma en cuenta el indice superior, solo el inferior, lista de comprension anidada, el resultado es una matriz
#Cuando el argumento de np.array es una iteracion anidada, genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#En python puro
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

Creating Arrays from Scratch

In [4]:
import numpy as np

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.random((3, 3))

array([[0.78572304, 0.84629938, 0.58258952],
       [0.54416831, 0.32718731, 0.70269988],
       [0.17040379, 0.8099344 , 0.03656451]])

In [12]:
np.random.normal(0, 1, (3, 3))

array([[-1.31955831, -0.29889383, -0.09706151],
       [ 0.98090042, -2.80872104, -0.26264636],
       [ 0.34259175, -0.12732456,  0.65182696]])

In [13]:
np.random.randint(0, 10, (3, 3))

array([[2, 4, 1],
       [3, 8, 5],
       [5, 4, 1]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [17]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [18]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [19]:
print("dtype:", x3.dtype)

dtype: int64


In [20]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x1[0]

np.int64(5)

In [23]:
x1[4]

np.int64(7)

In [24]:
x1[-1]

np.int64(9)

In [25]:
x1[-2]

np.int64(7)

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0,2]

np.int64(2)

In [29]:
x2[-1,-1] = 2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

#### Análisis Estadístico Básico con numPy

In [30]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


In [32]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [35]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


In [37]:
mediana = np.median(data)
mediana

np.float64(3.0)

In [38]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


In [ ]:
#media, desviacion, N° datos
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))