<a href="https://colab.research.google.com/github/PaclonkMei/MineriAdDatOs_177876/blob/main/Mineria_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer Parcial

### Introducción

https://jakevdp.github.io/PythonDataScienceHandbook/01.01-help-and-documentation.html

#### Conceptos

https://www.ibm.com/es-es/think/topics/data-mining

#### Ciencia de Datos

Ayuda y documentacion en Python

In [ ]:
#La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de pedir ayuda
len?

In [ ]:
#Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
#Otra forma de pedir ayuda con una lista
L?

In [ ]:
#Ejemplo de funcion
def square(a):
  return a ** 2

In [ ]:
help(square)

Help on function square in module __main__:

square(a)



In [ ]:
square??

In [ ]:
len??

In [ ]:
L.insert

<function list.insert(index, object, /)>

IPython Magic Commands


In [2]:
#Evalua el desempeño de la expresion respecto al tiempo, solo evalua una linea
%timeit L = [n ** 2 for n in range(1000)]

70 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
#El doble porcentaje es para evaluar el desempeño de varias lineas de tiempo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

81.4 µs ± 9.88 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [7]:
ls

sample_data/


In [8]:
!pwd

/content


In [9]:
contents = !ls

In [10]:
print(contents)

['sample_data']


In [13]:
directory = !pwd

In [14]:
print(directory)

['/content']


In [15]:
type(directory)

IPython.utils.text.SList

In [16]:
message = "Héloooou"

In [17]:
!echo = {message}

= Héloooou


In [18]:
%cd /content/

/content


In [19]:
%ls

sample_data/


In [20]:
%cd sample_data/

/content/sample_data


In [21]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [22]:
cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [23]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'f2883a46d164',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in IPython

In [24]:
#Importa numpy y renombralo como np
import numpy as np

In [25]:
#un arregl lineal de enteros, ND array, number dimention
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [26]:
#al hacer una lista con np, esta castea los diferentes numeros en un tipo, en este caso, flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [30]:
#podemos especificar que tipo queremos castear
np.array([3.14, 4, 2, 3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [31]:
np.array([3.14, 4, 2, 3], dtype='int')

array([3, 4, 2, 3])

In [32]:
#En rango no se toma en cuenta el indice superior, solo el inferior, lista de comprension anidada, el resultado es una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])